export const Icon = {
  Main_LOgo: require("../Assets/Icon/AppLogo.svg").default,
  Add_Logo: require("../Assets/Icon/Add.svg").default,
  Add_User_Blank: require("../Assets/Icon/Add_User_Blank.svg").default,
  Close_Logo: require("../Assets/Icon/Close.svg").default,
  Email_Logo: require("../Assets/Icon/Email.svg").default,
  ErrorInput_Logo: require("../Assets/Icon/ErrorInput.svg").default,
  Hide_Logo: require("../Assets/Icon/Hide.svg").default,
  Name_Logo: require("../Assets/Icon/Name.svg").default,
  Password_Logo: require("../Assets/Icon/Password.svg").default,
  UnPassword_Logo: require("../Assets/Icon/UnPassword.svg").default,
  Search_Logo: require("../Assets/Icon/Search.svg").default,
  Setting_Logo: require("../Assets/Icon/Setting.svg").default,
  UpdateUser_Logo: require("../Assets/Icon/UpdateUser.svg").default,
  UserProfile_Logo: require("../Assets/Icon/UserProfile.svg").default,
  UPArrow_Logo: require("../Assets/Icon/Up.svg").default,
  DownArrow_Logo: require("../Assets/Icon/Down.svg").default,
  BlankWhite: require("../Assets/Icon/BlankWhite.png"),
  FavIcon: require("../Assets/Icon/FavIcon.png"),
};
